development:
  sessions:
    default:
      database: pagpos_development
      hosts:
        - pagposv1.cloudapp.net
production:
  sessions:
    default:
      database: pagpos_production
      hosts:
        - pagposv1.cloudapp.net