test: &default

  # Credentials for REST APIs
  client_id: AePf_hCrGHwZuEJN0j8yNwNoNAFcFnwfHZryMYLcFSZLypo1w2FAj7sGJQdK
  client_secret: EFYgrhBsktlQWxEHOnWYrcd8LV4c64OFrPJuksW4dCrrEyNspLTt0Y6PsNF1

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: PAGPOSPayment
  # username: work-2009-facilitator_api1.windowslive.com
  # password: 1397581357
  # signature: AhsCG3FDWgTA7NVkA7zEeldLPt6PAdKXsBkDU1Id62FTuiLmX31CXRb5
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: work-2009-facilitator@windowslive.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  client_id: ATRPvxCqdlPqrKAnJyUaTqcEyNxH-iocZHyHCzzZPvyhW2OeP_Qat2gImJ-k
  client_secret: EH3t5xC0X-dJdpGApF3e2--mTWtUftNAJ63q8HaC3rWPNXNcFW0mtlIBSC-6
